### ISSUE TITLE
how to use it in c# .net Windows Application 

### ISSUE THREAD

**Issue by wasimjee** [langboost/curve25519-uwp#4]
how to use it in c# .net Windows Application  with framework 4.0
please help

**Comment by jeff-r-skillrev** [comment]
Just like with libaxolotl, I think this is probably just a NuGet issue. Try packaging the same DLLs into lib\dotnet (as well as lib\uap10.0 as it is already doing) by modifying Build.bat and the .nuspec file in the deploy folder on Github. That should get you moving. Submit a pull request when you're done.

**Comment by wasimjee** [comment]
I am using VS 2015 community edition, and I am getting the dll, but while adding it as reference in my windows desktop application c# with framework 4.0, it says
curve25519.dll could not be added. Please make sure the file is accessible, and it is a valid assembly or COM component

**Comment by wasimjee** [comment]
Sir Please guide me

**Comment by jeff-r-skillrev** [comment]
Upon further inspection, "classic" .NET apps were never meant to consume Windows Runtime components. Curve25519-uwp is a Windows Runtime component. You cannot use it from a classic .NET app as you are attempting to do. You can only use it from a universal windows app (UWP/UAP/"metro" app).

The C++ code would probably port to a traditional COM component just fine. Please contribute to the community by writing a COM component that encapsulates this curve25519 functionality.
